/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import exception.HandlerException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Detail;
import model.NhanVien;
import model.PhongBan;

/**
 *
 * @author Huy Trường
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    List<NhanVien> listNv = new ArrayList<>();
    List<PhongBan> listPb = new ArrayList<>();
    List<Detail> listDetail = new ArrayList<>();
    DefaultTableModel nv, pb, detail;
    String pathNv = "src/NV.txt";
    String pathPb = "src/PB.txt";
    String pathDetail = "src/QLNS.txt";
    Controller controller;

    public Form() {
        initComponents();
        controller = new Controller();
        listNv = controller.getFromFile(pathNv);
        listPb = controller.getFromFile(pathPb);
        listDetail = controller.getFromFile(pathDetail);
        if (!listNv.isEmpty())
            NhanVien.id = listNv.get(listNv.size()-1).getMa()+1;
        if (!listPb.isEmpty())
            PhongBan.id = listPb.get(listPb.size()-1).getMa()+1;
        nv = (DefaultTableModel) nvTBL.getModel();
        pb = (DefaultTableModel) pbTBL.getModel();
        detail = (DefaultTableModel) detailTBL.getModel();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nvTBL = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pbTBL = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        detailTBL = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nvTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Số điện thoại", "Địa chỉ", "Bậc"
            }
        ));
        jScrollPane1.setViewportView(nvTBL);

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addGap(0, 108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        pbTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Mô tả", "Hệ số"
            }
        ));
        jScrollPane2.setViewportView(pbTBL);

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton2)
                .addGap(0, 108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        detailTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Mã phòng ban", "Tên phòng ban", "Ngày"
            }
        ));
        jScrollPane3.setViewportView(detailTBL);

        jButton3.setText("Thêm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton3)
                .addGap(0, 108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new FormNhanVien(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new FormPhongBan(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new FormDetail(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    public List<NhanVien> getListNv() {
        return listNv;
    }

    public void setListNv(List<NhanVien> listNv) {
        this.listNv = listNv;
    }

    public List<PhongBan> getListPb() {
        return listPb;
    }

    public void setListPb(List<PhongBan> listPb) {
        this.listPb = listPb;
    }

    public List<Detail> getListDetail() {
        return listDetail;
    }

    public void setListDetail(List<Detail> listDetail) {
        this.listDetail = listDetail;
    }
    
    public void addNv(String ten, String diaChi, String sdt, String bac) {
        String message = NhanVien.checkFormat(ten, sdt, diaChi, bac);
        try {
            if (!message.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, message);
                throw new HandlerException(message);
            }
            listNv.add(new NhanVien(ten, sdt, diaChi, Integer.parseInt(bac)));
            controller.writeToFile(listNv, pathNv);
            showData();
        } catch (HandlerException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    public void addPb(String ten, String moTa, String heSo) {
        String message = PhongBan.checkFormat(ten, moTa, heSo);
        try {
            if (!message.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, message);
                throw new HandlerException(message);
            }
            listPb.add(new PhongBan(ten, moTa,Integer.parseInt(heSo)));
            controller.writeToFile(listPb, pathPb);
            showData();
        } catch (HandlerException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    public void addDetail(int maNv, int maPb ,String ngayValue) {
        NhanVien nhanVien = controller.getNv(listNv,maNv);
        PhongBan phongBan = controller.getPb(listPb,maPb);
        String message = "";
        if (ngayValue.matches("[^0-9]+"))
            message = "Ngày không hợp lệ";
        else 
            if (Integer.parseInt(ngayValue)<0 || Integer.parseInt(ngayValue)>31)
                message = "Ngày > 0 va < 32";
        try {
            if (!message.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, message);
                throw new HandlerException(message);
            }
            int index = controller.getIndex(listDetail, maNv, maPb);
            if (index != -2)
            {
                if (index == -1)
                    listDetail.add(new Detail(nhanVien, phongBan, Integer.parseInt(ngayValue)));
                else 
                    listDetail.get(index).setNgay(listDetail.get(index).getNgay()+Integer.parseInt(ngayValue));
                controller.writeToFile(listDetail, pathDetail);
                showData();
            }
            else 
                JOptionPane.showMessageDialog(rootPane, "1 nhân viên chỉ có thể ở 1 phòng ban");
        } catch (HandlerException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);

        }
    }
    public void showData() {
        nv.setRowCount(0);
        for (NhanVien nhanVien : listNv) {
            nv.addRow(new Object[]{nhanVien.getMa(), nhanVien.getTen(), nhanVien.getSdt(), nhanVien.getDiaChi(), nhanVien.getBac()});
        }
        pb.setRowCount(0);
        for (PhongBan phongBan : listPb) {
            pb.addRow(new Object[]{phongBan.getMa(), phongBan.getTen(), phongBan.getMoTa(), phongBan.getHeSo()});
        }
        detail.setRowCount(0);
        for (Detail value : listDetail) {
            detail.addRow(new Object[]{value.getNhanVien().getMa(), value.getNhanVien().getTen(), value.getPhongBan().getMa(), value.getPhongBan().getTen(),value.getNgay()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable detailTBL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable nvTBL;
    private javax.swing.JTable pbTBL;
    // End of variables declaration//GEN-END:variables
}
